第一章の課題２つ
hironoriohashi/JavaQuest pull request #1
Opened 2017-04-19 08:54 UTC by hironoriohashi

2017-04-19 08:54 UTC, hironoriohashi commented
レビューお願いします

2017-04-19 08:58 UTC, fossamagna requested changes

2017-04-19 08:58 UTC, fossamagna commented on Q1_3.java
> +      System.out.println("意外と\"Java\"って簡単だ。");
`意外と`ではなく`意外に`ではないですか？

2017-04-19 08:58 UTC, fossamagna commented on Q1_3.java
> +public class Q1_3{
ファイル名が`Kantan.java`じゃないですね。

2017-04-19 08:58 UTC, fossamagna commented on Q1_4.java
> +    System.out.println("おはよう。\nこんにちは。\nこんばんは。\n");
Windowsのコマンドプロンプトで実行しても問題なく同じ結果になるでしょうか？

2017-04-19 09:01 UTC, sakai-y requested changes

2017-04-19 09:01 UTC, sakai-y commented on Q1_4.java
> +//pabric class Aisatu{
`pabric`ww

2017-04-19 09:01 UTC, sakai-y commented on Q1_4.java
> +    System.out.println("おはよう。\nこんにちは。\nこんばんは。\n");
`Aisatu.java`の実行結果と同じになることを確認しましたか？
よく見ると、同じじゃないかも。

2017-04-19 09:01 UTC, sakai-y commented on Q1_3.java
> +public class Q1_3{
全体的に空白がなくて窮屈なので、[ここらへん](https://kazurof.github.io/GoogleJavaStyle-ja/#s4-6-whitespace)を参考に、見やすくしてみてください。

2017-04-20 02:56 UTC, fossamagna requested changes

2017-04-20 02:56 UTC, fossamagna commented on Q1_4.java
> +        System.out.println("おはよう。\r\nこんにちは。\r\nこんばんは。");
- 固定の改行コード(このコードだと`\r\n`)を指定すると実行環境(Windows, Linux, macOSなど)によって改行コードが違うので期待した結果と異なる(余計な文字が出力されたりする)ことになります。実行環境の改行コードを取得して利用するようにしましょう。
https://docs.oracle.com/javase/jp/8/docs/api/java/lang/System.html#lineSeparator--

- 問題にある`System.out,println()`を3回呼び出しているコードとは結果がことなりませんか？(改行コード足りない気がする)

2017-04-20 02:57 UTC, fossamagna requested changes

2017-04-20 02:57 UTC, fossamagna commented on Q1_4.java
> +//    System.out,println("こんばんは。");
`System.out,println("こんばんは。");`の`println`の前は`,`じゃなくて`.`ですね。

2017-04-20 02:59 UTC, fossamagna commented on Q1_4.java
> +        System.out.println("おはよう。\r\nこんにちは。\r\nこんばんは。");
あ、改行はたりますね。

2017-04-20 04:45 UTC, hironoriohashi commented
改めて修正しました。
レビューお願いします。

2017-04-20 04:46 UTC, sakai-y commented
- 改行コードがシステム依存になってるよ
- 空白がなくて窮屈だよ

が対応されていないと思われ。

2017-04-20 05:22 UTC, hironoriohashi commented
改めて修正しました。
レビューお願いします。

2017-04-20 05:24 UTC, sakai-y commented on Kantan.java
> +      System. out. println("意外に\"Java\"って簡単だ。");
「ここらへん」と書いたリンクの先をどう読んだら、こうなるんだ・・・（苦笑）

2017-04-20 05:39 UTC, hironoriohashi commented
改めて修正しました。
レビューお願いします。

2017-04-20 05:43 UTC, sakai-y commented on Kantan.java
> +    for( int i=0; i<3; i++ ){
もはやJavaじゃなくて日本語読解の領域かも知れない・・・。
例えば、`予約語（ if, for , catch ）とその行での開始小括弧 ( ( )の間。`とあったら、空白を入れるべきはどこかな。

2017-04-20 05:58 UTC, hironoriohashi commented
改めて修正しました。
レビューお願いします。

2017-04-20 05:59 UTC, sakai-y commented on Kantan.java
> +    for (int i=0; i<3; i++ ) {
せっかくなので、もう少し。
`すべての二項あるいは三項演算子の両側。`はできてますか？

2017-04-20 06:04 UTC, fossamagna commented on Kantan.java
> +    for (int i=0; i<3; i++ ) {
こういった類のものは [Checkstyle](http://checkstyle.sourceforge.net/) などで機械的に処理した方がいいですね。

2017-04-20 06:36 UTC, fossamagna commented on Q1_4.java
> +        }
インデントがずれていますね。この下の行も。

2017-04-20 06:44 UTC, t-kunou commented on Q1_4.java
> +        }
Eclipseを使っているならば、こういうのは手で直すのではなくctrl + shift + f すると良いと思います。

2017-04-20 07:05 UTC, hironoriohashi commented
改めて修正しました。
レビューお願いします。

2017-04-20 07:06 UTC, sakai-y approved these changes
LGTM

2017-04-20 07:12 UTC, t-kunou commented on Q1_4.java
> +        String str = System.getProperty("line.separator");
変数名を line_separator などにしたほうが読みやすいですね。
あと ``System.getProperty("line.separator");`` は古い書き方なので、``System.lineSeparator()``を使うと良さそうです。

2017-04-20 07:17 UTC, hironoriohashi commented
修正しました。
レビューお願いします。

2017-04-20 07:18 UTC, t-kunou commented
もう一声！
> 変数名を line_separator などにしたほうが読みやすいですね。

2017-04-20 07:21 UTC, hironoriohashi commented
修正しました。
レビューお願いします。

2017-04-20 07:26 UTC, t-kunou commented
良さそう 🙆 

因みに、Java8でStringに [join](https://docs.oracle.com/javase/jp/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.CharSequence...-) というメソッドが増えているのでこれを使うともっと良い感じに書けますよ。（ご参考まで）

2017-04-20 07:59 UTC, fossamagna approved these changes
LGTM

2017-04-21 01:47 UTC, sakai-y commented
マージしましょう。

2017-04-21 01:49 UTC, merged