11章の課題６つ
hironoriohashi/JavaQuest pull request #11
Opened 2017-05-01 07:11 UTC by hironoriohashi

11章の課題６つを作成しました。
レビューお願いします。

2017-05-01 07:30 UTC, sakai-y commented on Q11_4/Point.java
> + * 1行目、クラス宣言時に他のクラスから参照できるようpublicで宣言していないので、クラス宣言時にpublicを付けます。
元のコードのコンパイルエラーを解消するためにクラスをpublicにする必要があるということでしょうか？

2017-05-01 07:30 UTC, sakai-y commented on Q11_6/Rectangle.java
> +        if (this == null || rect == null) {
`this == null`
必要ですか？

2017-05-01 07:30 UTC, sakai-y commented on Q11_7/Rectangle.java
> +        OutputRect rect = new OutputRect();
`OutputRect`ってどこにあるんでしょうか。

2017-05-01 07:30 UTC, sakai-y commented on Q11_8/Rectangle.java
> +        w = w > 0 ? w : 0;
`setSize()`と同じことをここでやっているのは何故？

2017-05-01 07:30 UTC, sakai-y commented on Q11_8/Rectangle.java
> +        InputRect r1 = new InputRect();
`InputRect`？

2017-05-01 07:30 UTC, sakai-y commented on Q11_9/Rectangle.java
> +        Rectangle rect = new Rectangle();
ここでインスタンス生成する必要がありますか？

2017-05-01 07:30 UTC, sakai-y commented on Q11_9/Rectangle.java
> +        if ((x2 - x1) > 0 && (y2 - y1) > 0) {
引き算せず、単に大小比較でいいのでは。
あるいは、`x2 - x1`は、重なる領域の幅になるので、`if`の前に変数に格納しておいて、`if`の中で`setSize()`にそのまま渡すのもアリです。

2017-05-01 07:59 UTC, hironoriohashi commented on Q11_4/Point.java
> + * 1行目、クラス宣言時に他のクラスから参照できるようpublicで宣言していないので、クラス宣言時にpublicを付けます。
クラスの中にmainメソッドがあるのでpublicは必要ないです。
修正します。

2017-05-01 08:01 UTC, hironoriohashi commented on Q11_6/Rectangle.java
> +        if (this == null || rect == null) {
コンストラクタがあるので必要ないです。
修正します。

2017-05-01 08:03 UTC, sakai-y commented on Q11_6/Rectangle.java
> +        if (this == null || rect == null) {
> コンストラクタがあるので必要ない

ん？

2017-05-01 08:05 UTC, hironoriohashi commented on Q11_8/Rectangle.java
> +        w = w > 0 ? w : 0;
重複してます...
修正します。

2017-05-01 08:09 UTC, hironoriohashi commented on Q11_6/Rectangle.java
> +        if (this == null || rect == null) {
インスタンスを生成するときに引数を与えないとコンパイルエラーになるので値が`null`になることはないと考えています。

2017-05-01 08:11 UTC, hironoriohashi commented on Q11_7/Rectangle.java
> +        OutputRect rect = new OutputRect();
`workspace`で名前が被らないように違うファイル名で作り、修正し忘れていました。
修正します。

2017-05-01 08:12 UTC, sakai-y commented on Q11_6/Rectangle.java
> +        if (this == null || rect == null) {
`引数`とはコンストラクタの引数`w`と`h`を指している？

2017-05-01 08:12 UTC, hironoriohashi commented on Q11_8/Rectangle.java
> +        InputRect r1 = new InputRect();
`OutputRect`と同じ理由で修正し忘れていました。
修正します。

2017-05-01 08:13 UTC, hironoriohashi commented on Q11_9/Rectangle.java
> +        Rectangle rect = new Rectangle();
if文の中で宣言した方がいいです。
修正します。

2017-05-01 08:23 UTC, hironoriohashi commented on Q11_6/Rectangle.java
> +        if (this == null || rect == null) {
調べたらインスタンスが`null`だった場合に、メソッドを呼び出そうとすると`NullPointerException`という例外処理が行われることが分かりました。なので、`this == null`は必要ないという認識で合ってますか？

2017-05-01 08:26 UTC, sakai-y commented on Q11_6/Rectangle.java
> +        if (this == null || rect == null) {
はい。

2017-05-01 08:30 UTC, hironoriohashi commented on Q11_9/Rectangle.java
> +        if ((x2 - x1) > 0 && (y2 - y1) > 0) {
大小比較の方が分かりやすいので修正します。
また、`x2 - x1`と`y2 - y1`を変数に格納してメソッドに渡すように修正します。

2017-05-01 08:49 UTC, hironoriohashi commented
課題11－4のアクセス修飾子とコメント文
課題11－6の条件式
課題11－7のクラス名
課題11－8のクラス名と処理の重複
課題11－9のインスタンスの宣言場所とifの条件式
上記を修正しました。
レビューお願いします。

2017-05-01 09:02 UTC, sakai-y commented on Q11_8/Rectangle.java
> +        w = w > 0 ? w : 0;
`w`を補正してから`width`に代入していますが、１回で代入までしてしまいましょう。

2017-05-01 09:02 UTC, sakai-y commented on Q11_9/Rectangle.java
> +
不要な空行がありますね。

2017-05-01 09:02 UTC, sakai-y commented on Q11_9/Rectangle.java
> +        if (x2 > x1 && y2 > y1) {
重なる場合の処理が`if`ブロック内に書かれていますが、
これ以上処理を続行できないケースを早めにreturn（早期return）してしまうことで、本来の処理を関数のトップレベルに置くことができます。

2017-05-01 09:26 UTC, hironoriohashi commented
課題11-8 フィールドへの代入
課題11-9 空行の削除とif文の条件文の中の処理
上記を修正しました。
レビューお願いします。

2017-05-01 09:30 UTC, sakai-y requested changes

2017-05-01 09:30 UTC, sakai-y commented on Q11_9/Rectangle.java
> +        Rectangle rect = new Rectangle(w, h, x1, y1);
正しい結果にならなそうです。

2017-05-02 01:56 UTC, hironoriohashi commented on Q11_9/Rectangle.java
> +        Rectangle rect = new Rectangle(w, h, x1, y1);
コンストラクタで入力するのが間違っているということですか？

2017-05-02 02:09 UTC, sakai-y commented on Q11_9/Rectangle.java
> +        Rectangle rect = new Rectangle(w, h, x1, y1);
現状は正しいですね。
コンストラクタの引数の順番が指示通り（`x, y, width, heightを指定したもの`）になっていないだけでした。

2017-05-02 02:18 UTC, hironoriohashi commented on Q11_9/Rectangle.java
> +        Rectangle rect = new Rectangle(w, h, x1, y1);
コメント文との食い違いがあったのを確認しました。
修正します。

2017-05-02 02:24 UTC, hironoriohashi commented
コンストラクタの引数を修正しました。
レビューお願いします。

2017-05-02 02:51 UTC, sakai-y approved these changes
LGTM

2017-05-08 01:51 UTC, t-kunou commented on Q11_4/Point.java
> + * 5行目、メソッドにstatic修飾子があり、メソッドの外で宣言したフィールドxとyを使えないのでstaticを使いません。
メソッドにstatic修飾子があると ``x``, ``y`` が見れなくなる理由として、「メソッドの外で宣言したから」、だと不十分だと思います。
なぜstaticメソッドからは``x``, ``y``が見れないのでしょうか？

2017-05-08 02:09 UTC, t-kunou commented on Q11_9/Rectangle.java
> +    static int INITIAL_WIDTH = 10;
名前が全て大文字ということは定数ですので ``final`` を付けると良さそうですね

2017-05-08 02:47 UTC, hironoriohashi commented
課題11-9の定数にfinal修飾子を追加しました。
レビューお願いします。

2017-05-08 02:49 UTC, t-kunou commented
ヨ🈂️ソウ 🌟

2017-05-09 00:43 UTC, fossamagna approved these changes
LGTM

2017-05-09 01:21 UTC, merged