第二章の課題３つ
hironoriohashi/JavaQuest pull request #2
Opened 2017-04-19 08:56 UTC by hironoriohashi

レビューお願いします。

2017-04-19 09:33 UTC, sakai-y requested changes

2017-04-19 09:33 UTC, sakai-y commented on Q2_2.java
> +    for(int i=0; i<11; i++){
コードの意図として「10まで」なので、そのまま`i <= 10`とする方が意図が明確になります。

2017-04-19 09:33 UTC, sakai-y commented on Q2_3.java
> +        "、高さが" + height + "の台形の面積は" + ((double)(width1 + width2)/2 * height));
除算は誤差が生じるので、順番を変更可能な場合は後にした方がよいです。

2017-04-19 09:33 UTC, sakai-y commented on Q2_4.java
> +    System.out.println("10000 * 10000 = " + (long)(10000 * 10000));
そもそも `10000 x 10000`は`100000000`であって`1000000000`ではないよね。
で、このコードを実行すると、ちゃんと`100000000`と表示されます。

2017-04-20 02:46 UTC, t-kunou commented on Q2_4.java
> +    System.out.println("10000 * 10000 = " + (long)(10000 * 10000));
問題の原文が分からないのでエスパーですが、問題は ``100_0000 * 100_0000`` じゃないですかね。
そしてその結果が ``1410065408`` となるのは 、計算結果がintの範囲外だからです。 https://docs.oracle.com/javase/jp/6/api/constant-values.html#java.lang.Integer.MAX_VALUE

2017-04-20 02:55 UTC, sakai-y commented on Q2_4.java
> +    System.out.println("10000 * 10000 = " + (long)(10000 * 10000));
エスパー正解。原文確認したところ`100000`でした
＃`0`が１つ不足

2017-04-20 08:10 UTC, hironoriohashi commented
修正しました。
レビューお願いします。

2017-04-20 08:19 UTC, t-kunou commented on Q2_4.java
> +        System.out.println("100000 * 100000 = " + ((long) 100000 * 100000));
これ、どの値がlongにキャストされているか把握していますか？

2017-04-20 08:21 UTC, hironoriohashi commented on Q2_4.java
> +        System.out.println("100000 * 100000 = " + ((long) 100000 * 100000));
左辺の100,000がキャストされてると思っています。

2017-04-20 08:22 UTC, sakai-y requested changes

2017-04-20 08:22 UTC, sakai-y commented on Q2_3.java
> +                + "、高さが" + height + "の台形の面積は" + (height * (double) (width1 + width2) / 2));
単位が欲しいね。
ちなみに台形の面積の公式って、`( 上底 ＋ 下底 ) × 高さ ÷ 2`って習わなかった？
＃時代によって違うのかも

2017-04-20 08:22 UTC, sakai-y commented on Q2_4.java
> +//どのように修正したら正しく100000000と表示されるでしょうか。
これでも`10000000000`にならない？

2017-04-20 08:28 UTC, sakai-y commented on Q2_3.java
> +                + "、高さが" + height + "の台形の面積は" + (height * (double) (width1 + width2) / 2));
計算結果は一旦ローカル変数に代入してからprintしましょうか

2017-04-20 08:32 UTC, t-kunou commented on Q2_4.java
> +        System.out.println("100000 * 100000 = " + ((long) 100000 * 100000));
そうですね。
演算子の結合優先度が ``()``の方が ``*`` より高いので左辺がキャストされていると思います。 http://www.javaroad.jp/java_operator7.htm

ですが、演算子の優先度で読ませるのは辛い場合があるので、この場合は ``((long)100_000) * 100_000`` の方が読みやすいかと思います。

ついでにいうと、``100_000L``と書くとはじめからlongで値が作られるはずです。
https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

2017-04-20 08:41 UTC, hironoriohashi commented on Q2_3.java
> +                + "、高さが" + height + "の台形の面積は" + (height * (double) (width1 + width2) / 2));
分かりました。

2017-04-20 08:41 UTC, hironoriohashi commented on Q2_4.java
> +        System.out.println("100000 * 100000 = " + ((long) 100000 * 100000));
ご教授ありがとうございます。試してみます。

2017-04-20 08:49 UTC, hironoriohashi commented
修正しました。
レビューお願いします。

2017-04-20 08:52 UTC, sakai-y requested changes

2017-04-20 08:52 UTC, sakai-y commented on Q2_3.java
> +        double ans = ((width1 + width2) * height / 2);
外側の`(` `)`は不要です。

2017-04-20 08:52 UTC, sakai-y commented on Q2_3.java
> +        System.out.println("上底が" + width1 + "メートル、下底が" + width2
問題より相当大きいような

2017-04-20 08:52 UTC, sakai-y commented on Q2_4.java
> +        System.out.println("100000 * 100000 = " + (100_000L * 100_000));
右側も`L`付けよう

2017-04-20 08:59 UTC, hironoriohashi commented
修正しました。
レビューお願いします。

2017-04-20 09:00 UTC, sakai-y approved these changes
LGTM

2017-04-20 09:01 UTC, t-kunou commented on Q2_4.java
> +//どのように修正したら正しく100000000と表示されるでしょうか。
この辺のコメントはもう要らないですかね

2017-04-20 09:02 UTC, sakai-y commented on Q2_4.java
> +//どのように修正したら正しく100000000と表示されるでしょうか。
これ、「問題」だということにさっき気づきました。。。

2017-04-20 09:06 UTC, hironoriohashi commented on Q2_4.java
> +//どのように修正したら正しく100000000と表示されるでしょうか。
申し訳ないです。
問題の原文だと明示していませんでした。

2017-04-20 09:15 UTC, t-kunou commented on Q2_4.java
> +//どのように修正したら正しく100000000と表示されるでしょうか。
oh...なるほど！

2017-04-21 01:31 UTC, t-kunou commented
良いとおもます〜 ⭐️

2017-04-21 01:46 UTC, fossamagna approved these changes
LGTM

2017-04-21 01:50 UTC, merged