18章の課題２つ
hironoriohashi/JavaQuest pull request #23
Opened 2017-05-16 07:04 UTC by hironoriohashi

18章の課題
FindFile.javaと
Prime.javaを作成しました。
レビューお願いします。

2017-05-22 00:43 UTC, sakai-y requested changes

2017-05-22 00:43 UTC, sakai-y commented on Q18_2/FindFile1.java
> +            reader.close();
`close()`は`finally`で行った方がいいです。

2017-05-22 00:43 UTC, sakai-y commented on Q18_3/Prime1.java
> +                //ここでnを出力する
出力してないですね。

2017-05-22 00:43 UTC, sakai-y commented on Q18_3/Prime1.java
> +        for (int n = 0; n < MAX_PRIME; n++) {
`ここでnを出力する`で出力していれば、このループ不要ですね。
無駄に２セットのループをしてしまいます。

2017-05-22 02:08 UTC, hironoriohashi commented
FindFile1.javaの`.close()`を`finally`に移動し、
Prime.javaのファイルへの出力の処理を変更しました。
また、FindFile1.javaのテストコードも作成しました。
レビューお願いします。

2017-05-22 03:07 UTC, sakai-y commented on Q18_2/FindFile1.java
> +            if (reader != null) {
はい。`finally`で`close()`すると、ウザいことが分かりましたね。
そこで`try-with-resourcesです。

2017-05-22 03:07 UTC, sakai-y commented on Q18_2/FindFile1Test.java
> +    public void 引数にnullを入れた場合はNullPointerExceptionが返ってくる() {
このテストは不要かと。
＃分かってるなら対処しろ、と言われるだけですw

2017-05-22 05:48 UTC, hironoriohashi commented
FindFile1.javaのfinally文を削除してtry-with-resources文に変更し、
FindFile1Test.javaの引数に`null`を与えた場合のテストメソッドを削除しました。
レビューお願いします。

2017-05-23 06:01 UTC, sakai-y approved these changes
LGTM

2017-05-23 08:38 UTC, fossamagna approved these changes
LGTM

2017-05-24 02:42 UTC, merged

2017-05-30 08:29 UTC, shunji-yamaguchi commented on Q18_2/FindFile1.java
> +                    System.out.println(line);
行番号の出力を忘れてませんか？