19章の課題1つ
hironoriohashi/JavaQuest pull request #24
Opened 2017-05-17 02:33 UTC by hironoriohashi

19‐3の課題MyStringArrayList.javaを作成しました。
レビューお願いします。

2017-05-17 02:46 UTC, sakai-y requested changes
単体テスト向きなクラスなのでテストも作ってください。
きっとバグが見つかります。

2017-05-17 02:46 UTC, sakai-y commented on Q19_3/MyStringArrayList.java
> + * 「ArrauListの内部はどうなっているか」(p.269)を参考にして、
洗うリスト

2017-05-17 02:46 UTC, sakai-y commented on Q19_3/MyStringArrayList.java
> +        if (!(arrayCount < arraySize)) {
パッと見て分かりにくい条件式は避けましょう。

2017-05-17 09:00 UTC, hironoriohashi commented
コメントを修正し、メモリを使い切った場合に例外処理を投げるようにしました。
また、テストコードも作成しました。
レビューお願いします。

2017-05-18 00:22 UTC, sakai-y commented
テスト・・・動かしてみた？

2017-05-18 00:31 UTC, hironoriohashi commented
動かしてみましたが、私には分かりませんでした...

2017-05-18 06:28 UTC, hironoriohashi commented
if文の修正とthrowの追加を行いました。
レビューお願いします。

2017-05-18 06:44 UTC, sakai-y requested changes

2017-05-18 06:44 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void コンストラクタの動作を確認する() {
全体的に「やってみた」的なテストばかりですが、それではテストになりません。
◯◯した時には〜になること、と、結果が伴っている必要があります。

2017-05-18 06:44 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void コンストラクタの動作を確認する() {
例えば、これだと、コンストラクタを実行して、どうなれば正しいのか分かりませんね。

2017-05-18 06:44 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void 入出力テストをする() {
このテストクラスは`MyStringArrayList`をテストするものですよね？
このメソッドでテストしているのは何でしょうか。

2017-05-18 06:44 UTC, sakai-y commented on Q19_3/MyStringArrayList.java
> +    public void add(String s) throws OutOfMemoryError {
非検査例外は`throws`で宣言する必要はありません。

2017-05-18 06:44 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void メモリを使い切ってみる() {
メモリを使い切ったら`OutOfMemoryError`（＝OOMと略します）が発生することは確認できたと思いますが、メモリを確保できなかった場合にOOMを投げるのは`MyStringArrayList`が実装している機能ではないですよね？
なので、`MyStringArrayList`の**単体テスト**としては不要です。
＃結合テストやシステムテストでは別の話

逆にOOMを確認するなら、他のErrorは不要なの？って話になるので、必要十分なテストにしましょう。

2017-05-18 07:32 UTC, hironoriohashi commented
MyStringArrayList.javaのaddメソッドの`throws`を削除し、
テストコードのメソッド名を変更、
`OutOfMemoryError`を確認するテストメソッドを削除しました。
レビューお願いします。

2017-05-18 07:37 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void 中身を入れずにgetしてみる() {
これも「やってみた」の類です。
メソッド名でテストケースを表します。
「◯◯した時には〜になること」「◯◯の場合は〜であること」のような表現にしましょう。
＃全部ですね

2017-05-18 07:37 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void addで入力した値とgetで得る値が同じか確認する() {
もう１度確認しますが、これは何のテストをしていますか？

2017-05-18 08:10 UTC, hironoriohashi commented on Q19_3/MyStringArrayListTest.java
> +    public void addで入力した値とgetで得る値が同じか確認する() {
addメソッドとgetメソッドのテストをしています。

2017-05-18 08:13 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void addで入力した値とgetで得る値が同じか確認する() {
addとgetをテストするのにprintlnが必要？

2017-05-18 08:16 UTC, hironoriohashi commented on Q19_3/MyStringArrayListTest.java
> +    public void addで入力した値とgetで得る値が同じか確認する() {
必要ないです。修正します。

2017-05-18 08:18 UTC, t-kunou commented on Q19_3/MyStringArrayListTest.java
> +        for (int i = 0; i < 10; i++) {
一般的に、テストコードではあまり複雑な事をしないほうが良いです。（なぜなら複雑な事をするとテストコードのテストコードが必要になるので…）

何個かaddしてみる程度のことがしたいならループしなくてよいかと。

```java
testList.add(Integer.toString(0));
testList.add(Integer.toString(1));
testList.add(Integer.toString(2));
```

2017-05-18 08:47 UTC, hironoriohashi commented
テストコードのメソッド名の修正と
addとgetのテストメソッドの処理を変更しました。
レビューお願いします。

2017-05-18 08:55 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +        System.out.print(testList.size());
同じことでコメントもらわないように努力しましょう。

2017-05-18 08:55 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void getで中身のない要素を得ようとすると例外になること() {
２つ上のテストと確認してることは違うのかな。

2017-05-18 08:55 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void getしたときに中身が無いと例外になること() {
`中身が無い`とは？
次のテストケースの`負の数を渡すと`は条件として明快です。
`中身が無い`も、どうにかなりませんかね。

それと、`例外になること`より`IndexOutOfBoundsExceptionが発生すること`の方がよいです。

2017-05-18 08:55 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void teardown() {
なくてもいいですね。

2017-05-18 09:03 UTC, hironoriohashi commented on Q19_3/MyStringArrayListTest.java
> +    public void getしたときに中身が無いと例外になること() {
> 中身が無いとは？

中身が`null`だった場合を想定したテストでしたが、getメソッド内の条件文によって要素がない場合と同じ処理をされるので、要素がない場合のテストで十分な気がします。

2017-05-18 09:05 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void getしたときに中身が無いと例外になること() {
> getメソッド内の条件文によって要素がない場合と同じ処理をされる

これは、どこを指している？

2017-05-18 09:09 UTC, hironoriohashi commented on Q19_3/MyStringArrayListTest.java
> +    public void getしたときに中身が無いと例外になること() {
>> getメソッド内の条件文によって要素がない場合と同じ処理をされる

>これは、どこを指している？

条件文`if (n < 0 || n >= arrayCount)`の`n >= arrayCount`で同じようにtrueと判断されるところです。

2017-05-18 09:16 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void getしたときに中身が無いと例外になること() {
理解した。`中身がnull`ってところで`要素がnull`かと思ってしまった。
要素がない状態ですね。

・・・というように、「中身」は不明確です。

2017-05-19 01:12 UTC, hironoriohashi commented
@Afterのメソッドとインスタンスが`null`の場合のテストメソッドを削除し、
printlnの処理を削除、
メソッド名の変更を行いました。
レビューお願いします。

2017-05-19 03:15 UTC, t-kunou commented on Q19_3/MyStringArrayListTest.java
> +        assertNotNull(testList);
これってテストコードのテストしてませんか？

2017-05-19 03:15 UTC, t-kunou commented on Q19_3/MyStringArrayListTest.java
> +    public void getで要素のない配列を得ようとするとIndexOutOfBoundsExceptionになること() {
``要素のない配列`` ?
得ようとしているのはStringですよね。

2017-05-19 06:59 UTC, hironoriohashi commented on Q19_3/MyStringArrayListTest.java
> +    public void getで要素のない配列を得ようとするとIndexOutOfBoundsExceptionになること() {
`要素`ではないとしたら、どのように表現すれば良いですか？

2017-05-19 07:05 UTC, sakai-y commented on Q19_3/MyStringArrayListTest.java
> +    public void getで要素のない配列を得ようとするとIndexOutOfBoundsExceptionになること() {
このテストで確認したいことは何ですか？それを的確に表現すればよいです。
すくなくとも`要素のない配列を得よう`としているわけではないよね。

2017-05-19 07:09 UTC, t-kunou commented on Q19_3/MyStringArrayListTest.java
> +    public void getで要素のない配列を得ようとするとIndexOutOfBoundsExceptionになること() {
配列を使っているかどうかは、MyStringArrayListの内部実装の話ですよね。
テストとしては、結果が期待値通りであれば配列を使っているかどうかはどうでも良いのです。
``XXXという操作をした時YYYという値が取れること``がテストでしたいことで、YYYは配列ではないですよね？

2017-05-19 08:17 UTC, hironoriohashi commented on Q19_3/MyStringArrayListTest.java
> +        assertNotNull(testList);
> これってテストコードのテストしてませんか？

このコンストラクタのテストをしたい場合、`size`を取ってきて`0`だった場合に正常に行われたといった判断で大丈夫ですか？

2017-05-19 08:19 UTC, t-kunou commented on Q19_3/MyStringArrayListTest.java
> +        assertNotNull(testList);
もしやるならそうですね

2017-05-22 00:35 UTC, hironoriohashi commented
テストコードのメソッド名を変更し、
コンストラクタが動作したかを確認する処理を変更しました。
レビューお願いします。

2017-05-22 00:47 UTC, sakai-y approved these changes
LGTM

2017-05-22 01:26 UTC, t-kunou commented
良いと思います ⭐️

2017-05-23 05:07 UTC, fossamagna commented on Q19_3/MyStringArrayList.java
> +    private int arraySize;
`ar.length`で確認できるので。`arraySize`をプロパティ(インスタンスフィールド)として保持しておく必要はないように思います。

2017-05-23 05:17 UTC, hironoriohashi commented on Q19_3/MyStringArrayList.java
> +    private int arraySize;
> `ar.length`で確認できるので。`arraySize`をプロパティ(インスタンスフィールド)として保持しておく必要はないように思います。

確かに、同じ値が受け取れます。
`arraySize`は必要ないので削除します。

2017-05-23 05:28 UTC, hironoriohashi commented
MyStringArrayList.javaの変数arraySizeを削除しました。
レビューお願いします。

2017-05-23 06:18 UTC, fossamagna approved these changes
LGTM

2017-05-23 06:32 UTC, merged