Issues1の課題 StringUtils.javaとStringUtilsTest.java
hironoriohashi/JavaQuest pull request #25
Opened 2017-05-22 03:01 UTC by hironoriohashi

Issues1の課題 StringUtils.javaとStringUtirlsTest.javaを作成しました。
レビューお願いします。

2017-05-22 05:57 UTC, sakai-y requested changes

2017-05-22 05:57 UTC, sakai-y commented on StringUtils.java
> +        int anderCount = 0;
`under`かな。

2017-05-22 05:57 UTC, sakai-y commented on StringUtils.java
> +        ArrayList<Integer> upperString = new ArrayList<Integer>();
`Integer`のListなのに`upperString`・・・？

2017-05-22 05:57 UTC, sakai-y commented on StringUtils.java
> +            str.append(s.substring(i, i + 1));//文字を一文字ずつ追加
`charAt()`の方が分かりやすいような

2017-05-22 05:57 UTC, sakai-y commented on StringUtils.java
> +        return str.toString().toLowerCase();
`if (upperString.get(addAnderCount) == i) {`のブロック内では、`i`番目の文字が大文字と分かっているわけで、そこだけ小文字に変換すれば、ここで変換不要な文字まで対象に`toLowerCase()`する必要なくなりますよね。

2017-05-22 06:02 UTC, hironoriohashi commented on StringUtils.java
> +        ArrayList<Integer> upperString = new ArrayList<Integer>();
> `Integer`のListなのに`upperString`・・・？

大文字の箇所を覚えておくためだったので`upperString`にしました。
この場合、どういった変数名が適切でしょうか。

2017-05-22 07:42 UTC, hironoriohashi commented
変数名を修正し、
`substring()`を`charAt()`に変更し、
小文字への変換を処理を`append()`するときに行うように変更しました。
レビューお願いします。

2017-05-22 08:31 UTC, sakai-y commented on StringUtils.java
> +        ArrayList<Integer> upperStringSuffix = new ArrayList<Integer>();
suffixって、`接尾辞`ですね。何か後ろに付けるの？
このListには何が入るんでしょうか。
ループ内で`i`を入れてますよね。この`i`は何て言いますか？

2017-05-22 08:31 UTC, sakai-y commented on StringUtils.java
> +                    ch = Character.toLowerCase(s.charAt(i));
`s.charAt(i)`を改めてコールする必要はありますか？

2017-05-22 08:31 UTC, sakai-y commented on StringUtils.java
> +                if (upperStringSuffix.get(addUnderCount) == i) { //"_"を入れるかどうかの判断
これのelseがないのであれば、上のifとまとめていいのでは。
＃というか、ここでは意味的にまとめるべきのような

2017-05-22 09:00 UTC, hironoriohashi commented on StringUtils.java
> +        ArrayList<Integer> upperStringSuffix = new ArrayList<Integer>();
> ループ内でiを入れてますよね。このiは何て言いますか？

`index`のiだと認識してますが、合っていますか。

2017-05-22 09:01 UTC, sakai-y commented on StringUtils.java
> +        ArrayList<Integer> upperStringSuffix = new ArrayList<Integer>();
👍

2017-05-22 09:03 UTC, hironoriohashi commented on StringUtils.java
> +                if (upperStringSuffix.get(addUnderCount) == i) { //"_"を入れるかどうかの判断
まとめると`.get(addUnderCount)`から`IndexOutOfBoundsException`が投げられたので分けました。

2017-05-22 09:04 UTC, hironoriohashi commented on StringUtils.java
> +                    ch = Character.toLowerCase(s.charAt(i));
> `s.charAt(i)`を改めてコールする必要はありますか？

ありません。
修正します。

2017-05-22 09:04 UTC, sakai-y commented on StringUtils.java
> +                if (upperStringSuffix.get(addUnderCount) == i) { //"_"を入れるかどうかの判断
？

2017-05-23 01:02 UTC, hironoriohashi commented
StringUtils.javaの`upperStringSuffix`を`upperStringIndex`に変更し、
大文字がまだあるかどうかのif文を`_`を入れるかどうかのif文と統合、
s.charAt(i)の処理を一か所、変数chに置き換えました。
レビューお願いします。

2017-05-23 01:13 UTC, sakai-y commented on StringUtils.java
> +                if (upperStringSuffix.get(addUnderCount) == i) { //"_"を入れるかどうかの判断
> まとめると.get(addUnderCount)からIndexOutOfBoundsExceptionが投げられたので分けました。

これは結局どういうことだったの？

2017-05-23 01:16 UTC, sakai-y commented on StringUtils.java
> +                //大文字がまだあるかどうか,"_"を入れるかどうかの判断
謎のインデント

2017-05-23 01:16 UTC, sakai-y commented on StringUtilsTest.java
> +
空文字（`""`）を渡すテストを追加してみてください。

2017-05-23 01:16 UTC, sakai-y commented on StringUtils.java
> +            ch = s.charAt(i);
変数の宣言と代入、分ける必要ないですね。

2017-05-23 01:20 UTC, hironoriohashi commented on StringUtils.java
> +                if (upperStringSuffix.get(addUnderCount) == i) { //"_"を入れるかどうかの判断
if文の`&&`の前後を入れ替えると、.getで配列の大きさを超えたところから値を取ろうとすることがあるので、`addUderCount`が配列の大きさを超えたときに.getを使わないようif文を分けたのですが、`&&`の前後の式を入れ替えて解決しました。

2017-05-23 01:22 UTC, sakai-y commented on StringUtils.java
> +                if (upperStringSuffix.get(addUnderCount) == i) { //"_"を入れるかどうかの判断
よく分からないので、ダメだったコードを例示してください。

2017-05-23 01:24 UTC, hironoriohashi commented on StringUtils.java
> +                if (upperStringSuffix.get(addUnderCount) == i) { //"_"を入れるかどうかの判断
`if (upperStringIndex.get(addUnderCount) == i && addUnderCount < underCount) {`

2017-05-23 01:25 UTC, sakai-y commented on StringUtils.java
> +                if (upperStringSuffix.get(addUnderCount) == i) { //"_"を入れるかどうかの判断
ふむ。どうして入れ替えると解決したのか、説明してください。

2017-05-23 01:29 UTC, hironoriohashi commented on StringUtils.java
> +                if (upperStringSuffix.get(addUnderCount) == i) { //"_"を入れるかどうかの判断
先に`addUnderCount < underCount`の条件を満たしているかどうかの判断が行われ、満たしていなかった場合は`upperStringIndex.get(addUnderCount)  == i`の条件文の判断が行われないためだと考えています。

2017-05-23 01:33 UTC, sakai-y commented on StringUtils.java
> +                if (upperStringSuffix.get(addUnderCount) == i) { //"_"を入れるかどうかの判断
👍 
`&&`も`||`も、左から順に評価され、結果が決まった時点で、それ以降は評価されません。
＃`短絡評価`というらしい
＃C/C++も同じですよね

先に確認すべきことを先に書きましょう。

2017-05-23 01:38 UTC, hironoriohashi commented on StringUtils.java
> +                if (upperStringSuffix.get(addUnderCount) == i) { //"_"を入れるかどうかの判断
> 先に確認すべきことを先に書きましょう。

分かりました。確かにC/C++でも同じように書いていました。
> 短絡評価というらしい

左側が先に評価されるぐらいにしか知らなかったので`短絡評価`という単語は初めて聞きました。

2017-05-23 02:13 UTC, hironoriohashi commented on StringUtilsTest.java
> +
例外`IndexOutOfBoundsException`が返ってきますが、この場合は例外を受け取るのが適切でしょうか。それともメソッドに処理をさせて何かしらの値を返す方が適切でしょうか。

2017-05-23 02:16 UTC, sakai-y commented on StringUtilsTest.java
> +
「渡した文字列をスネークケースにして返すメソッド」に空文字を渡した場合に`IndexOutOfBoundsException`が発生するのが、仕様だと思えるかどうかです。

2017-05-23 02:17 UTC, hironoriohashi commented on StringUtilsTest.java
> +
そうは思わないので、例外が発生しないよう修正します。

2017-05-23 02:36 UTC, hironoriohashi commented
StringUtils.javaに引数の文字列が1文字未満だった場合の処理を追加し、変数chの宣言と代入を１行で行うよう変更し、インデントの修正を行い、
StringUtilsTest.javaに引数に空文字を与えた場合のテストメソッドを作成しました。

2017-05-23 02:44 UTC, sakai-y commented on StringUtils.java
> +        if (s.length() < 1) {
ちなみに、どうして、このガードが必要になったんでしょうか。
＃「空文字を渡すと例外が発生するから」という「外から見た動作」ではなく、コードのここがこうだから、という回答を期待

2017-05-23 02:44 UTC, sakai-y commented on StringUtilsTest.java
> +    public void toSnakeCaseに空文字を渡すと空文字が返ってくる() {
「〜こと」という名前にしましょう。

2017-05-23 02:55 UTC, hironoriohashi commented on StringUtils.java
> +        if (s.length() < 1) {
空文字だった場合、`str.append()`の処理が一度も行われることなく、`str`の配列の長さが0で`return str.toString();`の時に値の入っていない要素を参照し、`IndexOutOfBoundsException`が発生するので、文字列の長さが1未満の場合、空文字を返すようにしました。

2017-05-23 02:59 UTC, sakai-y commented on StringUtils.java
> +        if (s.length() < 1) {
new しただけで全く文字を追加していない`StringBuilder`に対して、`toString()`を呼び出すと`IndexOutOfBoundsException`が発生するってこと？
やってみてください。

2017-05-23 03:02 UTC, hironoriohashi commented on StringUtils.java
> +        if (s.length() < 1) {
通りました。もう一度原因を考えます。

2017-05-23 03:04 UTC, sakai-y commented on StringUtils.java
> +        if (s.length() < 1) {
もう一度、ガードを外して失敗したテストを実行し、その時のスタックトレースを確認すればいいですよね。
想像は不要です。事実を確認しましょう。

2017-05-23 03:05 UTC, hironoriohashi commented on StringUtils.java
> +        if (s.length() < 1) {
s.charAt(0)で例外が発生していました。

2017-05-23 04:03 UTC, sakai-y commented on StringUtils.java
> +        if (s.length() < 1) {
そうですね。先頭の文字をチェックしている箇所ですね。
で、せっかく最初に大文字の数をチェックしているんで、先頭も含めて数えて、変換の必要がなければ処理終了、としてしまうことで、「ためのガード」が不要になりませんかね。

2017-05-23 05:09 UTC, hironoriohashi commented
StringUtils.javaを大文字が1文字もなければ引数を返すように変更し、
StringUtilsTest.javaのテストコードのメソッド名を変更しました。
レビューお願いします。

2017-05-23 06:08 UTC, sakai-y approved these changes
LGTM

2017-05-23 06:08 UTC, sakai-y commented on StringUtils.java
> +        if (underCount == 0) {
👍

2017-05-23 06:19 UTC, fossamagna approved these changes
LGTM

2017-05-23 06:33 UTC, merged