Issues2の課題 の作成
hironoriohashi/JavaQuest pull request #26
Opened 2017-05-22 08:01 UTC by hironoriohashi

Issues2の課題,Calculator.javaとCalculatorTest.javaを作成しました。
レビューお願いします。

2017-05-22 08:38 UTC, sakai-y requested changes

2017-05-22 08:38 UTC, sakai-y commented on Calculator.java
> +        return a/b;
checkstyleが何か言いそう。

2017-05-22 08:38 UTC, sakai-y commented on CalculatorTest.java
> +        assertThat(calculator.divide(6, 0), is(0));
ゼロが返ってくることを期待しているかのようなテストコードですね。
メソッド呼び出した結果は不要で、呼び出しの副作用としての例外を確認するテストなら、アサーション不要です。

2017-05-22 09:06 UTC, hironoriohashi commented on Calculator.java
> +        return a/b;
`/`の前後に空白を入れ忘れました。
修正します。

2017-05-22 09:07 UTC, hironoriohashi commented on CalculatorTest.java
> +        assertThat(calculator.divide(6, 0), is(0));
例外を期待しているのであれば、メソッドの実行だけで十分です。
修正します。

2017-05-23 02:46 UTC, sakai-y commented on CalculatorTest.java
> +    public void devideの第2引数にゼロを渡してIllegalArgumentExceptionが返ってくること() {
細かいですが、例外は「返ってくる」ものではないです。
＃`ヒント`の記述を参考に

2017-05-23 05:39 UTC, hironoriohashi commented
CalculatorTest.javaのテストコードの例外を期待するメソッド名を`返ってくる`から`送出される`に変更しました。
レビューお願いします。

2017-05-23 06:11 UTC, sakai-y approved these changes
LGTM

2017-05-23 08:23 UTC, sakai-y commented
よく見たら何故かコンフリクトしてますね。
全部ルートにファイル置いてるからか・・・

2017-05-25 03:19 UTC, fossamagna approved these changes
LGTM

2017-05-25 04:35 UTC, merged