第7章の課題３つ
hironoriohashi/JavaQuest pull request #7
Opened 2017-04-25 05:12 UTC by hironoriohashi

7章の課題３つを作成しました。
レビューお願いします。

2017-04-25 06:13 UTC, fossamagna requested changes

2017-04-25 06:13 UTC, fossamagna commented on MakeHtml.java
> +                String head = line.substring(0, 1);
これだと、改行だけ入力すると例外がでるんじゃないかな？

2017-04-25 06:13 UTC, fossamagna commented on Q7_2.java
> +        int j = 0;
`j`の宣言は最初の`while`ループのブロック内で宣言したほうがスコープが小さくて済みますね。

2017-04-25 06:24 UTC, sakai-y requested changes

2017-04-25 06:24 UTC, sakai-y commented on MakeHtml.java
> +            System.out.println("<!DECTPYE html>");
`DECTPYE`
問題をよく見ましょう。

2017-04-25 07:47 UTC, t-kunou commented on MakeHtml.java
> +                    line = line.replace("■", "");
入力ファイルで、
```
■ □■□■□私のホームページへようこそ！□■□■□
```
と来るとどうなりますか？

2017-04-25 07:53 UTC, hironoriohashi commented on MakeHtml.java
> +                    line = line.replace("■", "");
line.replace("■","");の処理によって
`<h1>□□□私のホームページへようこそ！□□□</h1>`
と表示されると思います。

2017-04-25 07:57 UTC, t-kunou commented on MakeHtml.java
> +                    line = line.replace("■", "");
そうですね。

問題で、 ``入力行が"■"で始まっていたら、■を取り除いた残りの文字列を"<h1>"と"</h1>"ではさんで改行付きで出力する。`` となっていて、どちらとも取れる書き方ではありますが、おそらく先頭の■以外を潰すのは意図していない結果では無いかと思います。
（見出しのフォーマット変換がしたいので、文言を変えないようが良いですよね）

2017-04-25 07:58 UTC, fossamagna submitted a review, later dismissed

2017-04-25 08:57 UTC, hironoriohashi commented
Q7_2.javaのjの変数を宣言する場所を変更
MakeHtml.javaの出力処理を変更し、入力を制限するためにファイル操作の処理を追加しました。
レビューお願いします。

2017-04-25 09:22 UTC, t-kunou commented on MakeHtml.java
> +            System.out.println("引数を与えないでください");
問題とやっていることが変わってしまってますが、どういう話の流れでこうなりました？　（オフラインでの指摘ですか？）

2017-04-25 23:59 UTC, sakai-y commented on MakeHtml.java
> + * 標準出力に出すプログラムMakeHtmlを作ってください。
`標準入力から`〜`標準出力に`ですよ。

2017-04-26 00:44 UTC, hironoriohashi commented
フォルダ操作の処理を削除し、文字列がなかった場合に終了するようにしました。
レビューお願いします。

2017-04-26 00:53 UTC, t-kunou commented
せっかくなので squash してコミットログを綺麗にするとよいですね。
``rebase -i head~2`` で b47965f0dea468af1aaffc73c6a7f5b06f1d8fc0 と
 b23bbbd2a0876f28e1b202cafa8e2962fd1871fa を一つのコミットに纏めて、force pushしてみて下さい。

2017-04-26 00:59 UTC, fossamagna requested changes

2017-04-26 00:59 UTC, fossamagna commented on MakeHtml.java
> +            System.out.println("<!DECTPYE html>");
問題(コード内のコメント) : `DECTYPE`
回答(コード) : `DECTPYE`
期待値?(hello(0).html) : `DOCTPYE`

と全部違いますね。どれがい正解なのか？どれも正解じゃないのか？確認してみてください。

2017-04-26 01:16 UTC, hironoriohashi commented
ログの統合と誤字の修正をしました。
レビューお願いします。

2017-04-26 01:26 UTC, fossamagna commented on MakeHtml.java
> +            System.out.println("<!DOCTPYE html>");
`DOCTYPE`ですよね。落ち着いて修正しましょう。他にも同じような間違いがないか見直してください。

2017-04-26 01:28 UTC, sakai-y commented on MakeHtml.java
> +                    break;
空行は許可しない仕様でしたっけ。

2017-04-26 01:31 UTC, hironoriohashi commented on MakeHtml.java
> +                    break;
課題にそのような表記はありませんでした。修正します。

2017-04-26 02:23 UTC, hironoriohashi commented
誤字の修正と空行で処理を終了しないように変更しました。
レビューお願いします。

2017-04-26 02:31 UTC, sakai-y requested changes

2017-04-26 02:31 UTC, sakai-y commented on MakeHtml.java
> +                    System.out.println("<p></p>");
（もう少し頑張ってもらおうかな。）

これは、`入力がルール3にもルール4にも当てはまらない`のケースですよね。
同じケースに対する処理が、下の`switch`の`default`にもありますね。
これを１つにして欲しいです。

で、なんでこの`if`が必要かと言うと、`head`に１文字目を入れたいからなので、`head`を使わないようにしてみてください。

2017-04-26 03:03 UTC, hironoriohashi commented
if文を削除し、例外処理を回避する処理を追加しました。
レビューお願いします。

2017-04-26 03:52 UTC, hironoriohashi commented
空白が足りなかったので追加しました。

2017-04-26 04:04 UTC, sakai-y commented on MakeHtml.java
> +                line = line + " ";
難しいことになっちゃったねぇ。

`String.startsWith()`を使ってみましょう。
そうすると多分、`switch`使えなくなる。

どうしても`switch`使いたい場合は、`head`を復活させてもいいけど、「段落」の処理は１つで。

2017-04-26 04:42 UTC, hironoriohashi commented
switch文をif文に変更しました。
レビューお願いします。

2017-04-26 04:50 UTC, sakai-y commented on MakeHtml.java
> +                    System.out.println("<h1>" + line.substring(1, (line.length())) + "</h1>");
実は`String#substring()`には引数が１つのものがあります。
[リファレンス](http://docs.oracle.com/javase/jp/8/docs/api/java/lang/String.html)で確認してみましょう。

2017-04-26 04:50 UTC, sakai-y commented on hello.txt
> +�����̃z�[���y�[�W�ւ悤����
このファイル、GitHubだと読めませんね。何故こうなるのか、理由を考えて、対策してみましょう。

2017-04-27 04:48 UTC, hironoriohashi commented
hello.txtの文字コードをUTF-8に変更し、そのファイルを読み込めるようにMakeHtml.javaを変更しました。
レビューお願いします。

2017-04-27 04:49 UTC, sakai-y commented on MakeHtml.java
> +            reader.skip(1);
このskipは何ですか？

2017-04-27 04:51 UTC, hironoriohashi commented on MakeHtml.java
> +            reader.skip(1);
読み込んだ時になぜか最初の文字に`?`が加わっていたのでそれを無視するために入れました。

2017-04-27 04:53 UTC, fossamagna commented on MakeHtml.java
> +            reader.skip(1);
多分、[BOM](https://ja.wikipedia.org/wiki/%E3%83%90%E3%82%A4%E3%83%88%E3%82%AA%E3%83%BC%E3%83%80%E3%83%BC%E3%83%9E%E3%83%BC%E3%82%AF)だね。

2017-04-27 05:46 UTC, hironoriohashi commented
MakeHtml.javaのskipを削除し、別のエディタでhello.txtを作成しました。
レビューお願いします。

2017-04-27 05:49 UTC, t-kunou commented on hello.txt
> +■私のホームページへようこそ
結局、文字化けていた原因は BOMが付いていたからですかね。
もしかすると、このファイルならば読む時にcharsetの指定が要らないんじゃないでしょうか？

2017-04-27 06:01 UTC, sakai-y commented on hello.txt
> +■私のホームページへようこそ
@hironoriohashi charset指定が必要な理由を説明できますか？

2017-04-27 06:04 UTC, sakai-y commented on MakeHtml.java
> +            BufferedReader reader = new BufferedReader(new InputStreamReader(System.in, "UTF-8"));
`"UTF-8"`と直接指定するより、`Charset`版がいいかも。指定する`Charset`は`StandardCharsets`に定義されているものを使ってください。

2017-04-27 06:07 UTC, hironoriohashi commented on hello.txt
> +■私のホームページへようこそ
Windowsの標準入力の文字コードの初期設定が`Shift_JIS`で、`UTF-8`を読み込むために指定が必要だったと考えています。

2017-04-27 06:11 UTC, sakai-y commented on hello.txt
> +■私のホームページへようこそ
`InputStreamReader`の文字コード指定なし版の説明を読んでみてください。

2017-04-27 06:36 UTC, hironoriohashi commented on hello.txt
> +■私のホームページへようこそ
プラットフォームによってデフォルトの文字セットが違うからだと考えられます。

2017-04-27 06:37 UTC, sakai-y commented on hello.txt
> +■私のホームページへようこそ
そう。で、大橋君が実行した環境ではデフォルト文字セットがUTF-8ではなかったから、指定する必要があったわけですね。

2017-04-28 00:20 UTC, hironoriohashi commented
文字コードの指定を"UTF-8"からStandardCharsets.UTF_8に変更しました。
レビューお願いします。

2017-04-28 00:21 UTC, sakai-y approved these changes
LGTM

2017-04-28 00:45 UTC, fossamagna approved these changes
LGTM

2017-04-28 01:03 UTC, t-kunou commented
よさそう 👍

2017-04-28 01:38 UTC, merged

2017-05-30 04:48 UTC, shunji-yamaguchi commented on MakeHtml.java
> +                    System.out.println("<h1>" + line.substring(1, (line.length())) + "</h1>");
`str.substring(int n)`でstr文字列のn番目から末尾までの部分文字列を取得できます。
なのでこの場合、`line.substring(1) `と書くこともできます。参考までに。