9章の課題4つ
hironoriohashi/JavaQuest pull request #9
Opened 2017-04-27 08:36 UTC by hironoriohashi

9章の課題４つ作成しました。
レビューお願いします。

2017-04-27 10:03 UTC, fossamagna requested changes

2017-04-27 10:03 UTC, fossamagna commented on SelectGreeting.java
> +            System.out.println("番号は0～" + message.length + "の範囲で指定してください");
`番号は0～2の範囲で指定してください。`という出力にはならなさそうです。

2017-04-28 00:30 UTC, hironoriohashi commented
SelectGreeting.javaの出力を修正しました。
レビューお願いします。

2017-04-28 00:44 UTC, sakai-y commented on SelectGreeting.java
> +            System.exit(0);
正しく実行できずに終了するケースですが、終了コード`0`は妥当でしょうか。

2017-04-28 01:37 UTC, hironoriohashi commented on SelectGreeting.java
> +            System.exit(0);
引数の数が適切でない点だけなので正常終了で良いと考えました。

2017-04-28 01:40 UTC, sakai-y commented on SelectGreeting.java
> +            System.exit(0);
このプログラムを実行した人が意図した動作をしなかったわけですよね。
例えば、これがツールチェーンの途中だったり、スクリプトからの実行だったりすると、正しい結果が得られないのに正常終了しちゃうと困るのです。

2017-04-28 01:41 UTC, sakai-y commented on SelectGreeting.java
> +            System.exit(0);
ちなみにC言語知ってたと思うので、`sysexit.h`ってのを見てみてください。ググると出てきます。

2017-04-28 02:21 UTC, hironoriohashi commented on SelectGreeting.java
> +            System.exit(0);
今回の場合ですと、コマンドラインによるエラーなので`64`を入れるという認識で合っていますか

2017-04-28 02:22 UTC, sakai-y commented on SelectGreeting.java
> +            System.exit(0);
この定義に従う必要なないですが、少なくとも、`EX_USAGE`が定義されているということは正常終了ではないことが分かると思います。
今回は`0`以外であればOKです。

2017-04-28 02:27 UTC, hironoriohashi commented on SelectGreeting.java
> +            System.exit(0);
分かりました。では修正します。

2017-04-28 02:35 UTC, hironoriohashi commented
SelectGreeting.javaのSystem.exit(0)をSystem.exit(1)に変更しました。
レビューお願いします。

2017-04-28 02:37 UTC, sakai-y approved these changes
LGTM

2017-04-28 03:36 UTC, fossamagna approved these changes
LGTM

2017-04-28 03:58 UTC, merged